language: go
go:
 - 1.9.2
 - 1.8.x
 - master

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
 - go test -v ./... -coverprofile=c.out

after_script:
  - ./cc-test-reporter after-build